version: '3.7'
services:
  whereshouldigo:
    container_name: whereshouldigo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - ./node_modules:/app/node_modules
    ports:
      - '8081:8080'
    command: >
      sh -c "node node_modules/node-sass/scripts/install.js &&
             npm run serve"